package com.training.todo.entity;

import com.training.todo.enums.TodoStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

@Entity
@Table(name = "tasks")
public class Tasks {
    /**
     * id: Primary Key
     * @GeneratedValue ensures that the values are generated by the database automatically.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * title: The Task Title
     *
     * nullable = false ensures that a title is mandatory for tasks.
     */
    @Column(nullable = false)
    private String title;
    /**
     * description: The description of the task.
     */
    @Column
    private String description;

    /**
     * status: Current status of the todo.
     *
     * The database will stores enum as Strings in database.
     * {"PENDING", "UPCOMING", "COMPLETED"}
     *
     * Java utilizes TodoStatus.PENDING or such notations.
     * But, database stores the enum values.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TodoStatus status;

    /**
     * createdAt: Timestamp of task creation
     *
     * This value is set only once and cannot be overwritten or updated.
     */
    @Column(updatable = false)
    private LocalDateTime createdAt;

    // CONSTRUCTORS

    // Default Constructor
    public Tasks() {
    }

    /**
     * Constructor with all fields
     * Used in the service when creating new todos
     */
    public Tasks(String title, String description,
                 TodoStatus status, LocalDateTime createdAt) {
        this.title = title;
        this.description = description;
        this.status = status;
        this.createdAt = createdAt;
    }

    // Getters - Reading values
    public Long getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public TodoStatus getStatus() {
        return status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }


    // Setters - Writing values
    public void setId(Long id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setStatus(TodoStatus status) {
        this.status = status;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "Task{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", status=" + status +
                ", createdAt=" + createdAt +
                '}';
    }
}