# App Name
spring.application.name=Users

# Server Port: User Service runs on Port 8081
server.port=8081

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/users_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
# update means automatically create/update tables based on entity classes
spring.jpa.hibernate.ddl-auto=update
# show-sql ensures that the SQL Queries are printed in the console
spring.jpa.show-sql=true
# format-sql makes the SQL queries readable
spring.jpa.properties.hibernate.format_sql=true
# dialect tells Hibernate the project uses PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---> JWT Configuration <---
# Will be configured later.

# Logging
logging.level.com.event.users=DEBUG
logging.level.org.springframework.web=INFO

# Show detailed error messages
server.error.include-message=always
server.error.include-binding-errors=always