# App Name
spring.application.name=Users

# Server Port: User Service runs on Port 8081
server.port=8081

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/users_db
spring.datasource.username=root
spring.datasource.password=root

# JPA Configuration
# update means automatically create/update tables based on entity classes
spring.jpa.hibernate.ddl-auto=update
# show-sql ensures that the SQL Queries are printed in the console
spring.jpa.show-sql=true
# format-sql makes the SQL queries readable
spring.jpa.properties.hibernate.format_sql=true

# ---> JWT Configuration <---
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=1800000

# Logging
logging.level.com.event.users=DEBUG
logging.level.org.springframework.web=INFO

# Show detailed error messages
server.error.include-message=always
server.error.include-binding-errors=always